name: Biagio Antonelli
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
future: false
include:
  - favicon.ico

# Syntax highlighting settings
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

